// Generated by gencpp from file top_2_quad/my_message.msg
// DO NOT EDIT!


#ifndef TOP_2_QUAD_MESSAGE_MY_MESSAGE_H
#define TOP_2_QUAD_MESSAGE_MY_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Float64.h>

namespace top_2_quad
{
template <class ContainerAllocator>
struct my_message_
{
  typedef my_message_<ContainerAllocator> Type;

  my_message_()
    : header()
    , posizione()
    , handle()
    , precisione()  {
    }
  my_message_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , posizione(_alloc)
    , handle(_alloc)
    , precisione(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _posizione_type;
  _posizione_type posizione;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _handle_type;
  _handle_type handle;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _precisione_type;
  _precisione_type precisione;




  typedef boost::shared_ptr< ::top_2_quad::my_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::top_2_quad::my_message_<ContainerAllocator> const> ConstPtr;

}; // struct my_message_

typedef ::top_2_quad::my_message_<std::allocator<void> > my_message;

typedef boost::shared_ptr< ::top_2_quad::my_message > my_messagePtr;
typedef boost::shared_ptr< ::top_2_quad::my_message const> my_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::top_2_quad::my_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::top_2_quad::my_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace top_2_quad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'top_2_quad': ['/home/matteo/top_2_quad_WS/src/top_2_quad/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::top_2_quad::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::top_2_quad::my_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::top_2_quad::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::top_2_quad::my_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::top_2_quad::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::top_2_quad::my_message_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::top_2_quad::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8f5b0d9387022f2ce04fe1bd04c1a60";
  }

  static const char* value(const ::top_2_quad::my_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8f5b0d9387022f2ULL;
  static const uint64_t static_value2 = 0xce04fe1bd04c1a60ULL;
};

template<class ContainerAllocator>
struct DataType< ::top_2_quad::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "top_2_quad/my_message";
  }

  static const char* value(const ::top_2_quad::my_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::top_2_quad::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
geometry_msgs/Point posizione\n\
\n\
std_msgs/Int32 handle\n\
\n\
std_msgs/Float64 precisione\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::top_2_quad::my_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::top_2_quad::my_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.posizione);
      stream.next(m.handle);
      stream.next(m.precisione);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::top_2_quad::my_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::top_2_quad::my_message_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "posizione: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.posizione);
    s << indent << "handle: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.handle);
    s << indent << "precisione: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.precisione);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOP_2_QUAD_MESSAGE_MY_MESSAGE_H
